#!/usr/bin/env python3
"""Probe Codex OAuth concurrency assumptions without printing credential values.

Default operations are metadata-only. Any real Codex model call requires
``run-one --real`` so the probe cannot burn model time by accident.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any


_JWTISH = re.compile(r"\beyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{8,}\b")
_SECRETISH = re.compile(r"\b(?:sk-|sess-|authsess_)[A-Za-z0-9_-]{12,}\b")


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def pinned_codex_binary(root: Path) -> Path:
    return root / ".codex-pinned" / "node_modules" / ".bin" / "codex"


def canonical_codex_home(root: Path) -> Path:
    return root / ".codex-pinned" / "config"


def read_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as fh:
        value = json.load(fh)
    if not isinstance(value, dict):
        raise ValueError(f"{path} did not contain a JSON object")
    return value


def _file_digest(path: Path) -> str | None:
    if not path.is_file():
        return None
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _decode_jwt_claims(token: str | None) -> dict[str, Any] | None:
    if not token or token.count(".") < 2:
        return None
    try:
        payload = token.split(".", 2)[1]
        payload += "=" * ((4 - len(payload) % 4) % 4)
        decoded = base64.urlsafe_b64decode(payload.encode("ascii"))
        claims = json.loads(decoded)
    except Exception:
        return None
    return claims if isinstance(claims, dict) else None


def token_metadata(token: str | None, *, now: int | None = None) -> dict[str, Any]:
    now = int(time.time()) if now is None else now
    meta: dict[str, Any] = {"present": bool(token), "jwt": False}
    claims = _decode_jwt_claims(token)
    if not claims:
        return meta
    exp = claims.get("exp")
    iat = claims.get("iat")
    nbf = claims.get("nbf")
    meta.update(
        {
            "jwt": True,
            "issuer": claims.get("iss"),
            "audience_type": type(claims.get("aud")).__name__ if "aud" in claims else None,
            "scope_count": len(claims.get("scp") or []),
            "has_session_id_claim": "session_id" in claims,
            "issued_at": iat,
            "not_before": nbf,
            "expires_at": exp,
            "seconds_remaining": exp - now if isinstance(exp, int) else None,
            "expired": exp <= now if isinstance(exp, int) else None,
            "lifetime_seconds": exp - iat if isinstance(exp, int) and isinstance(iat, int) else None,
        }
    )
    return meta


def inspect_home(home: Path, *, now: int | None = None) -> dict[str, Any]:
    auth_path = home / "auth.json"
    result: dict[str, Any] = {
        "codex_home": str(home),
        "auth_json_present": auth_path.is_file(),
    }
    if not auth_path.is_file():
        return result
    auth = read_json(auth_path)
    tokens = auth.get("tokens") if isinstance(auth.get("tokens"), dict) else {}
    result.update(
        {
            "auth_mode": auth.get("auth_mode"),
            "openai_api_key_present": bool(auth.get("OPENAI_API_KEY")),
            "last_refresh_present": bool(auth.get("last_refresh")),
            "tokens": {
                "access_token": token_metadata(tokens.get("access_token"), now=now),
                "id_token": token_metadata(tokens.get("id_token"), now=now),
                "refresh_token_present": bool(tokens.get("refresh_token")),
                "account_id_present": bool(tokens.get("account_id")),
            },
        }
    )
    return result


def _private_dir(path: Path, *, force: bool = False) -> None:
    if path.exists():
        if not force:
            raise FileExistsError(f"{path} already exists; pass --force to replace it")
        shutil.rmtree(path)
    path.mkdir(parents=True, mode=0o700)
    os.chmod(path, 0o700)


def _toml_string(value: str) -> str:
    return json.dumps(value)


def write_minimal_config(home: Path, trust_cwd: Path | None) -> None:
    lines = [
        "# Generated by tools/probe_codex_oauth_concurrency.py.",
        "# No secrets live in this config file.",
        "",
        "[tui.model_availability_nux]",
        '"gpt-5.5" = 4',
        "",
    ]
    if trust_cwd is not None:
        lines.extend(
            [
                f"[projects.{_toml_string(str(trust_cwd.resolve(strict=False)))}]",
                'trust_level = "trusted"',
                "",
            ]
        )
    (home / "config.toml").write_text("\n".join(lines), encoding="utf-8")


def seed_ephemeral_home(
    canonical_home: Path,
    output_home: Path,
    *,
    trust_cwd: Path | None = None,
    refresh_token_mode: str = "omit",
    force: bool = False,
) -> dict[str, Any]:
    """Create an isolated Codex home for probing.

    The child home receives access/id credential material copied from the
    canonical home, but never receives the canonical refresh token. The caller
    chooses whether the refresh token key is omitted, empty, or a local poison
    sentinel so probes can discover what the Codex CLI accepts.
    """
    auth = read_json(canonical_home / "auth.json")
    tokens = auth.get("tokens") if isinstance(auth.get("tokens"), dict) else {}
    _private_dir(output_home, force=force)
    write_minimal_config(output_home, trust_cwd)
    child_tokens = {
        key: tokens[key]
        for key in ("access_token", "id_token", "account_id")
        if tokens.get(key)
    }
    if refresh_token_mode == "empty":
        child_tokens["refresh_token"] = ""
    elif refresh_token_mode == "poison":
        child_tokens["refresh_token"] = "invalid-refresh-token-for-probe"
    elif refresh_token_mode != "omit":
        raise ValueError(f"unknown refresh_token_mode {refresh_token_mode!r}")
    child_auth = {
        "auth_mode": auth.get("auth_mode"),
        "OPENAI_API_KEY": None,
        "tokens": child_tokens,
        "last_refresh": auth.get("last_refresh"),
    }
    auth_path = output_home / "auth.json"
    auth_path.write_text(json.dumps(child_auth, indent=2) + "\n", encoding="utf-8")
    os.chmod(auth_path, 0o600)
    return {
        "seeded_home": str(output_home),
        "refresh_token_mode": refresh_token_mode,
        "refresh_token_present": "refresh_token" in child_tokens and bool(child_tokens["refresh_token"]),
        "auth_json_mode": oct(auth_path.stat().st_mode & 0o777),
        "home_mode": oct(output_home.stat().st_mode & 0o777),
        "token_metadata": {
            "access_token": token_metadata(child_tokens.get("access_token")),
            "id_token": token_metadata(child_tokens.get("id_token")),
        },
    }


def _redact(text: str) -> str:
    text = _JWTISH.sub("<redacted-jwt>", text)
    text = _SECRETISH.sub("<redacted-secret>", text)
    return text


def run_one(
    root: Path,
    home: Path,
    cwd: Path,
    *,
    prompt: str,
    model: str,
    real: bool,
    timeout_s: int,
) -> dict[str, Any]:
    binary = pinned_codex_binary(root)
    argv = [
        str(binary),
        "exec",
        "-m",
        model,
        "--json",
        "--skip-git-repo-check",
        "--sandbox",
        "read-only",
        "-C",
        str(cwd),
        prompt,
    ]
    result: dict[str, Any] = {
        "real": real,
        "codex_binary": str(binary),
        "codex_home": str(home),
        "cwd": str(cwd),
        "argv_shape": [arg if arg != prompt else "<prompt>" for arg in argv],
    }
    if not real:
        result["would_run"] = True
        return result
    auth_before = _file_digest(home / "auth.json")
    env = dict(os.environ)
    env["CODEX_HOME"] = str(home)
    env.pop("OPENAI_API_KEY", None)
    env.pop("ANTHROPIC_API_KEY", None)
    proc = subprocess.run(
        argv,
        cwd=str(cwd),
        env=env,
        text=True,
        capture_output=True,
        timeout=timeout_s,
        check=False,
    )
    result.update(
        {
            "returncode": proc.returncode,
            "stdout_tail": _redact(proc.stdout[-4000:]),
            "stderr_tail": _redact(proc.stderr[-4000:]),
            "auth_json_changed": auth_before != _file_digest(home / "auth.json"),
        }
    )
    return result


def run_many(
    root: Path,
    canonical_home: Path,
    seat_root: Path,
    workspace_root: Path,
    *,
    count: int,
    refresh_token_mode: str,
    prompt: str,
    model: str,
    real: bool,
    timeout_s: int,
    force: bool,
) -> dict[str, Any]:
    if count < 1:
        raise ValueError("--count must be >= 1")
    seat_root.mkdir(parents=True, exist_ok=True)
    workspace_root.mkdir(parents=True, exist_ok=True)
    canonical_auth_before = _file_digest(canonical_home / "auth.json")

    seats: list[dict[str, Any]] = []
    seat_auth_before: dict[str, str | None] = {}
    for idx in range(1, count + 1):
        seat_id = f"seat-{idx:03d}"
        home = seat_root / seat_id / "config"
        cwd = workspace_root / seat_id
        cwd.mkdir(parents=True, exist_ok=True)
        seed = seed_ephemeral_home(
            canonical_home,
            home,
            trust_cwd=cwd,
            refresh_token_mode=refresh_token_mode,
            force=force,
        )
        seat_auth_before[seat_id] = _file_digest(home / "auth.json")
        seats.append({"seat_id": seat_id, "home": str(home), "cwd": str(cwd), "seed": seed})

    result: dict[str, Any] = {
        "real": real,
        "count": count,
        "seat_root": str(seat_root),
        "workspace_root": str(workspace_root),
        "refresh_token_mode": refresh_token_mode,
        "seats": seats,
    }
    if not real:
        result["would_run"] = True
        return result

    runs: list[dict[str, Any]] = []
    with ThreadPoolExecutor(max_workers=count) as pool:
        future_to_seat = {
            pool.submit(
                run_one,
                root,
                Path(seat["home"]),
                Path(seat["cwd"]),
                prompt=prompt,
                model=model,
                real=True,
                timeout_s=timeout_s,
            ): seat["seat_id"]
            for seat in seats
        }
        for future in as_completed(future_to_seat):
            seat_id = future_to_seat[future]
            try:
                payload = future.result()
            except Exception as exc:
                payload = {"seat_id": seat_id, "exception": type(exc).__name__, "message": _redact(str(exc))}
            payload["seat_id"] = seat_id
            runs.append(payload)
    result["runs"] = sorted(runs, key=lambda row: row.get("seat_id", ""))
    result["ok_count"] = sum(1 for row in runs if row.get("returncode") == 0)
    result["auth_json_changes"] = {
        "canonical_auth_json_changed": canonical_auth_before
        != _file_digest(canonical_home / "auth.json"),
        "seat_auth_json_changed": [
            {
                "seat_id": seat["seat_id"],
                "auth_json_changed": seat_auth_before[seat["seat_id"]]
                != _file_digest(Path(seat["home"]) / "auth.json"),
            }
            for seat in seats
        ],
    }
    return result


def _print_json(payload: dict[str, Any]) -> int:
    print(json.dumps(payload, indent=2, sort_keys=True))
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=repo_root())
    sub = parser.add_subparsers(dest="command", required=True)

    inspect_cmd = sub.add_parser("inspect", help="Inspect canonical auth metadata without values")
    inspect_cmd.add_argument("--home", type=Path)

    seed_cmd = sub.add_parser("seed-home", help="Create an isolated ephemeral CODEX_HOME")
    seed_cmd.add_argument("--output", type=Path, required=True)
    seed_cmd.add_argument("--canonical-home", type=Path)
    seed_cmd.add_argument("--trust-cwd", type=Path)
    seed_cmd.add_argument("--refresh-token-mode", choices=["omit", "empty", "poison"], default="omit")
    seed_cmd.add_argument("--force", action="store_true")

    run_cmd = sub.add_parser("run-one", help="Run or preview one tiny Codex probe turn")
    run_cmd.add_argument("--home", type=Path, required=True)
    run_cmd.add_argument("--cwd", type=Path, required=True)
    run_cmd.add_argument("--model", default="gpt-5.5")
    run_cmd.add_argument(
        "--prompt",
        default="Reply with exactly: CODEX_OAUTH_PROBE_OK. Do not run tools.",
    )
    run_cmd.add_argument("--timeout-s", type=int, default=180)
    run_cmd.add_argument("--real", action="store_true", help="Actually invoke Codex")

    many_cmd = sub.add_parser("run-many", help="Seed N ephemeral homes and run/preview concurrent probes")
    many_cmd.add_argument("--canonical-home", type=Path)
    many_cmd.add_argument("--seat-root", type=Path, required=True)
    many_cmd.add_argument("--workspace-root", type=Path, required=True)
    many_cmd.add_argument("--count", type=int, required=True)
    many_cmd.add_argument("--refresh-token-mode", choices=["omit", "empty", "poison"], default="omit")
    many_cmd.add_argument("--model", default="gpt-5.5")
    many_cmd.add_argument(
        "--prompt",
        default="Reply with exactly: CODEX_OAUTH_PROBE_OK. Do not run tools.",
    )
    many_cmd.add_argument("--timeout-s", type=int, default=180)
    many_cmd.add_argument("--force", action="store_true")
    many_cmd.add_argument("--real", action="store_true", help="Actually invoke Codex concurrently")

    args = parser.parse_args(argv)
    root = args.repo_root.resolve(strict=False)
    if args.command == "inspect":
        home = (args.home or canonical_codex_home(root)).resolve(strict=False)
        return _print_json(inspect_home(home))
    if args.command == "seed-home":
        canonical = (args.canonical_home or canonical_codex_home(root)).resolve(strict=False)
        payload = seed_ephemeral_home(
            canonical,
            args.output.resolve(strict=False),
            trust_cwd=args.trust_cwd,
            refresh_token_mode=args.refresh_token_mode,
            force=args.force,
        )
        return _print_json(payload)
    if args.command == "run-one":
        payload = run_one(
            root,
            args.home.resolve(strict=False),
            args.cwd.resolve(strict=False),
            prompt=args.prompt,
            model=args.model,
            real=args.real,
            timeout_s=args.timeout_s,
        )
        return _print_json(payload)
    if args.command == "run-many":
        payload = run_many(
            root,
            (args.canonical_home or canonical_codex_home(root)).resolve(strict=False),
            args.seat_root.resolve(strict=False),
            args.workspace_root.resolve(strict=False),
            count=args.count,
            refresh_token_mode=args.refresh_token_mode,
            prompt=args.prompt,
            model=args.model,
            real=args.real,
            timeout_s=args.timeout_s,
            force=args.force,
        )
        return _print_json(payload)
    raise AssertionError(args.command)


if __name__ == "__main__":
    raise SystemExit(main())
